#NAME: SHUBHAM SHARMA
#ROLL NO: 18i190002
#COURSE: MSC PHD OR
reset;
option solver gurobi;
model ex3.mod;
solve;
display z1,z2,z3,z4,z5,z6,b0,b1,b2,residual,con1.lb,con1.ub,con1.body,con2.lb,con2.ub,con2.body,con3.lb,con3.ub,con3.body,con4.lb,con4.ub,con4.body,con5.lb,con5.ub,con5.body,con6.lb,con6.ub,con6.body,con7.lb,con7.ub,con7.body,con8.lb,con8.ub,con8.body,con9.lb,con9.ub,con9.body,con10.lb,con10.ub,con10.body,con11.lb,con11.ub,con11.body,con12.lb,con12.ub,con12.body;
